CREATE DATABASE backendDb;

USE backendDb;

CREATE TABLE
  IF NOT EXISTS cars (
    id INT AUTO_INCREMENT PRIMARY KEY,
    marke VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    year INT NOT NULL
  );